export const ADDON_CATS = ['Smart Phone', 'Tablet'];

export const COLORS = {
  'Bar Phone':   ['Black', 'White'],
  'Smart Phone': ['Midnight Black', 'Starlight White', 'Ocean Blue', 'Forest Green', 'Sunset Gold', 'Mystic Purple', 'Coral Pink', 'Titanium Grey'],
  'Tablet':      ['Midnight Black', 'Starlight White', 'Ocean Blue', 'Titanium Grey'],
  'Earbuds':     ['Black', 'White', 'Blue'],
  'Smart Watch': ['Black', 'Silver', 'Rose Gold', 'Blue'],
  'Power Bank':  ['Black', 'White'],
  'Others':      ['Black', 'White'],
};

export const DEF = [
  { category: 'Bar Phone',   name: 'ITEL 2165',          ram: '',    storage: '',     unitPrice: 402,  srp: 1699  },
  { category: 'Bar Phone',   name: 'ITEL 5032',          ram: '',    storage: '',     unitPrice: 487,  srp: 1999  },
  { category: 'Bar Phone',   name: 'POWER 120',          ram: '',    storage: '',     unitPrice: 531,  srp: 2199  },
  { category: 'Bar Phone',   name: '9310 NEO',           ram: '',    storage: '',     unitPrice: 999,  srp: 2999  },
  { category: 'Smart Phone', name: 'A50C',               ram: '2GB', storage: '32GB', unitPrice: 2603, srp: 2799  },
  { category: 'Smart Phone', name: 'A50C',               ram: '2GB', storage: '64GB', unitPrice: 2789, srp: 2999  },
  { category: 'Smart Phone', name: 'A50',                ram: '3GB', storage: '64GB', unitPrice: 2882, srp: 3099  },
  { category: 'Smart Phone', name: 'A50',                ram: '4GB', storage: '64GB', unitPrice: 2976, srp: 3199  },
  { category: 'Smart Phone', name: 'A80',                ram: '4GB', storage: '128GB',unitPrice: 3719, srp: 3999  },
  { category: 'Smart Phone', name: 'A90',                ram: '3GB', storage: '128GB',unitPrice: 3403, srp: 3699  },
  { category: 'Smart Phone', name: 'A90',                ram: '4GB', storage: '256GB',unitPrice: 4047, srp: 4499  },
  { category: 'Smart Phone', name: 'A100C',              ram: '3GB', storage: '64GB', unitPrice: 4139, srp: 4899  },
  { category: 'Smart Phone', name: 'A100C',              ram: '3GB', storage: '128GB',unitPrice: 4599, srp: 5299  },
  { category: 'Smart Phone', name: 'A200',               ram: '3GB', storage: '128GB',unitPrice: 4415, srp: 5199  },
  { category: 'Smart Phone', name: 'CITY 100',           ram: '4GB', storage: '128GB',unitPrice: 3680, srp: 3999  },
  { category: 'Smart Phone', name: 'CITY 100',           ram: '8GB', storage: '128GB',unitPrice: 5059, srp: 5799  },
  { category: 'Smart Phone', name: 'P55 4G',             ram: '8GB', storage: '256GB',unitPrice: 4415, srp: 4799  },
  { category: 'Smart Phone', name: 'P55+ 4G',            ram: '8GB', storage: '256GB',unitPrice: 4959, srp: 5399  },
  { category: 'Smart Phone', name: 'P55 5G',             ram: '6GB', storage: '128GB',unitPrice: 5059, srp: 5499  },
  { category: 'Smart Phone', name: 'P70',                ram: '4GB', storage: '128GB',unitPrice: 4875, srp: 5599  },
  { category: 'Smart Phone', name: 'P70',                ram: '4GB', storage: '256GB',unitPrice: 4600, srp: 5199  },
  { category: 'Smart Phone', name: 'RS4',                ram: '8GB', storage: '128GB',unitPrice: 5519, srp: 5999  },
  { category: 'Smart Phone', name: 'RS4',                ram: '8GB', storage: '256GB',unitPrice: 5979, srp: 6599  },
  { category: 'Smart Phone', name: 'RS4',                ram: '12GB',storage: '256GB',unitPrice: 6439, srp: 7199  },
  { category: 'Smart Phone', name: 'S25',                ram: '8GB', storage: '128GB',unitPrice: 4836, srp: 5599  },
  { category: 'Smart Phone', name: 'S25 Ultra',          ram: '8GB', storage: '256GB',unitPrice: 7439, srp: 7999  },
  { category: 'Smart Phone', name: 'S25 Ultra',          ram: '8GB', storage: '512GB',unitPrice: 9299, srp: 9999  },
  { category: 'Smart Phone', name: 'S26 Ultra',          ram: '8GB', storage: '128GB',unitPrice: 7360, srp: 7999  },
  { category: 'Smart Phone', name: 'S26 Ultra',          ram: '8GB', storage: '256GB',unitPrice: 9659, srp: 10999 },
  { category: 'Tablet',      name: 'VISTA TAB GO',       ram: '4GB', storage: '64GB', unitPrice: 4875, srp: 5299  },
  { category: 'Tablet',      name: 'VISTA TAB 10',       ram: '4GB', storage: '128GB',unitPrice: 5114, srp: 5499  },
  { category: 'Tablet',      name: 'VISTA TAB 30',       ram: '4GB', storage: '128GB',unitPrice: 5393, srp: 5799  },
  { category: 'Tablet',      name: 'VISTA TAB 30S',      ram: '4GB', storage: '128GB',unitPrice: 7360, srp: 7999  },
  { category: 'Tablet',      name: 'VISTA TAB 30 PRO',   ram: '8GB', storage: '256GB',unitPrice: 9199, srp: 9999  },
  { category: 'Earbuds',     name: 'EARBUDS NEO',        ram: '',    storage: '',     unitPrice: 319,  srp: 1299  },
  { category: 'Earbuds',     name: 'EARPHONE BUDS AIR 2',ram: '',    storage: '',     unitPrice: 359,  srp: 1795  },
  { category: 'Smart Watch', name: '011 SMART WATCH',    ram: '',    storage: '',     unitPrice: 400,  srp: 1699  },
  { category: 'Smart Watch', name: '020 SMART WATCH',    ram: '',    storage: '',     unitPrice: 495,  srp: 2199  },
  { category: 'Smart Watch', name: '015 SMART WATCH',    ram: '',    storage: '',     unitPrice: 520,  srp: 2099  },
  { category: 'Smart Watch', name: '023 SMART WATCH',    ram: '',    storage: '',     unitPrice: 577,  srp: 2399  },
  { category: 'Smart Watch', name: 'APEX N10',           ram: '',    storage: '',     unitPrice: 1630, srp: 6299  },
  { category: 'Power Bank',  name: 'T144',               ram: '',    storage: '',     unitPrice: 239,  srp: 999   },
  { category: 'Power Bank',  name: 'A1421',              ram: '',    storage: '',     unitPrice: 560,  srp: 2299  },
  { category: 'Others',      name: 'PP131A (TAB 30 PRO)',ram: '',    storage: '',     unitPrice: 799,  srp: 3199  },
  { category: 'Others',      name: 'PK131A (TAB 30 PRO)',ram: '',    storage: '',     unitPrice: 1199, srp: 4799  },
  { category: 'Others',      name: 'Leather Case (TAB 10)',ram:'',   storage: '',     unitPrice: 199,  srp: 799   },
  { category: 'Others',      name: 'Leather Case (TAB 30)',ram:'',   storage: '',     unitPrice: 199,  srp: 799   },
];
